DB_URL = 'postgresql://postgres:@localhost/ces'
DEBUG = True
RECAPTCHA_USE_SSL = True
RECAPTCHA_PUBLIC_KEY = '6LeYIbsSAAAAACRPIllxA7wvXjIE411PfdB2gt2J'
RECAPTCHA_PRIVATE_KEY = '6LeYIbsSAAAAAJezaIq3Ft_hSTo0YtyeFG-JgRtu'
SECRET_KEY = 'secret'
